#ifndef __GIT_VERSION_H__
#define __GIT_VERSION_H__
#define GIMP_GIT_VERSION "GIMP_2_10_28"
#define GIMP_GIT_VERSION_ABBREV "9f9ff10"
#define GIMP_GIT_LAST_COMMIT_YEAR "2021"
#endif /* __GIT_VERSION_H__ */
