#ifndef __GIT_VERSION_H__
#define __GIT_VERSION_H__
#define GIMP_GIT_VERSION "GIMP_2_10_36"
#define GIMP_GIT_VERSION_ABBREV "1651e6e"
#define GIMP_GIT_LAST_COMMIT_YEAR "2023"
#endif /* __GIT_VERSION_H__ */
