#ifndef __GIT_VERSION_H__
#define __GIT_VERSION_H__
#define GIMP_GIT_VERSION "GIMP_2_10_38"
#define GIMP_GIT_VERSION_ABBREV "a8b1173"
#define GIMP_GIT_LAST_COMMIT_YEAR "2024"
#endif /* __GIT_VERSION_H__ */
